#!/usr/bin/env python3
"""Generate concise role command catalogs from the canonical registry."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def render(role: dict, commands: list[dict]) -> str:
    rows = []
    catalog = Path(role["commandCatalog"])
    for command in commands:
        prompt = Path(command["prompt"])
        relative = prompt.relative_to(catalog.parent)
        effects = ", ".join(f"`{effect}`" for effect in command["effects"])
        rows.append(
            f"| `{command['id']}` | `{command['alias']}` | "
            f"[{prompt.stem}]({relative.as_posix()}) | {effects} |"
        )
    table = "\n".join(rows)
    return f"""# {role['displayName']} workflows

<!-- Generated by tools/sync_command_catalogs.py from virtualboard.json. -->

Load only the workflow that matches the current user request. Do not announce a
persona or print this full catalog merely because the role was selected. Show the
catalog when the user asks what is available or when a short choice is needed to
disambiguate the request.

| Command ID | Alias | Workflow | Possible effects |
|---|---|---|---|
{table}

IDs and aliases are globally unique. The effect list is a ceiling, not blanket
permission. Read the selected workflow's generated command contract, stay within
the active task, and obtain explicit authorization for every effect whose policy
in `virtualboard.json` is `explicit-required`.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    contract = json.loads((ROOT / "virtualboard.json").read_text(encoding="utf-8"))
    drift: list[str] = []
    for role in contract["roles"]:
        commands = [command for command in contract["commands"] if command["role"] == role["id"]]
        if not commands:
            print(f"ERROR: role {role['id']} has no registered workflows", file=sys.stderr)
            return 1
        path = ROOT / role["commandCatalog"]
        expected = render(role, commands)
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual != expected:
            if args.write:
                path.write_text(expected, encoding="utf-8")
            else:
                drift.append(str(path.relative_to(ROOT)))

    if drift:
        for path in drift:
            print(f"ERROR: command catalog is out of date: {path}", file=sys.stderr)
        return 1
    verb = "Synchronized" if args.write else "Verified"
    print(f"{verb} {len(contract['roles'])} role command catalogs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
