#!/usr/bin/env python3
"""Generate or verify shared HTML-renderer instructions in report workflows."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HEADING_RE = re.compile(
    r"^#{2,3}\s+(?:\d+\.\s+)?Optional\s*(?::|—|-)\s*Generate Branded HTML Report\s*$",
    re.MULTILINE,
)
TEMPLATE_RE = re.compile(r"templates/reports/html/([a-z0-9]+(?:-[a-z0-9]+)*\.html)")
TEMPLATE_ARGUMENT_RE = re.compile(
    r"--template\s+([a-z0-9]+(?:-[a-z0-9]+)*)\b"
)


def replacement(template_name: str) -> str:
    template_id = template_name.removesuffix(".html")
    return f"""## Optional: Generate Branded HTML Report

<!-- Generated by tools/sync_report_instructions.py. -->

When the user requests `--html`, “as HTML,” “branded HTML,” or structured
`format: html`, write the Markdown artifact first and then use the shared strict
renderer. Do not implement placeholder substitution in the agent.

Template source: `$VB_ROOT/templates/reports/html/{template_name}`.

1. Resolve `VB_ROOT` as described in `AGENTS.md`.
2. Read `$VB_ROOT/templates/reports/README.md`, then print the authoritative
   placeholder manifest:

   ```bash
   python3 "$VB_ROOT/tools/render_report.py" \\
     --template {template_id} \\
     --describe
   ```

3. Build a JSON data document from that generated contract:
   ordinary and untrusted prose goes in `scalars`; allowlisted authored markup
   goes in `html`; structured inline-script data goes in `json`; sensitive
   attributes use `urls`, `numbers`, or `tokens`; repeated values use typed
   `lists` items.
4. Run:

   ```bash
   python3 "$VB_ROOT/tools/render_report.py" \\
     --template {template_id} \\
     --data <typed-render-data.json> \\
     --output <markdown-report-path-with-html-extension>
   ```

5. Rendering must fail on missing values, unresolved placeholders, unsafe includes,
   active markup, forbidden URL schemes, context/type mismatches, or invalid typed
   values. Never downgrade such a failure to a warning.
6. Report both Markdown and HTML paths. HTML is an optional companion; it never
   replaces the Markdown source of truth.
"""


def expected_text(path: Path) -> str | None:
    text = path.read_text(encoding="utf-8")
    matches = list(HEADING_RE.finditer(text))
    if not matches:
        return None
    if len(matches) != 1:
        raise ValueError(f"expected one HTML instruction heading in {path}")
    suffix = text[matches[0].start() :]
    templates = sorted(set(TEMPLATE_RE.findall(suffix)))
    if not templates:
        # Upgrade an earlier generated block that named only the CLI template ID.
        template_ids = sorted(set(TEMPLATE_ARGUMENT_RE.findall(suffix)))
        templates = [f"{template_id}.html" for template_id in template_ids]
    if len(templates) != 1:
        raise ValueError(
            f"expected one report template reference after HTML heading in {path}, found {templates}"
        )
    return text[: matches[0].start()] + replacement(templates[0])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    contract = json.loads((ROOT / "virtualboard.json").read_text(encoding="utf-8"))
    candidates = [ROOT / command["prompt"] for command in contract["commands"]]
    report_files = 0
    errors: list[str] = []
    for path in candidates:
        try:
            expected = expected_text(path)
        except (OSError, UnicodeError, ValueError) as exc:
            errors.append(str(exc))
            continue
        if expected is None:
            continue
        report_files += 1
        actual = path.read_text(encoding="utf-8")
        if args.write:
            path.write_text(expected, encoding="utf-8")
        elif actual != expected:
            errors.append(f"out-of-date HTML renderer instructions: {path.relative_to(ROOT)}")

    if report_files != 21:
        errors.append(f"expected 21 report workflows, found {report_files}")
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    action = "Updated" if args.write else "Verified"
    print(f"{action} shared renderer instructions in {report_files} workflows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
